### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by nstetter** [Nanoseb/ncTelegram#36] opened 2018-06-20 07:31 UTC
Traceback (most recent call last):
  File "/bin/nctelegram", line 93, in <module>
    ncTelegram.Telegram_ui(config_full)
  File "/usr/lib/python3.6/site-packages/ncTelegram/__init__.py", line 73, in __init__
    self.msg_widget = MessageWidget(self)
  File "/usr/lib/python3.6/site-packages/ncTelegram/ui_msgwidget.py", line 25, in __init__
    self.get_history()
  File "/usr/lib/python3.6/site-packages/ncTelegram/ui_msgwidget.py", line 60, in get_history
    self.print_msg(msg)
  File "/usr/lib/python3.6/site-packages/ncTelegram/ui_msgwidget.py", line 194, in print_msg
    self.focus_position = self.pos
  File "/usr/lib/python3.6/site-packages/urwid/listbox.py", line 578, in set_focus
    raise IndexError("Can't set focus, ListBox is empty")
IndexError: Can't set focus, ListBox is empty
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1499, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
read: Connection reset by peer

System:
Manjaro, 4.14.48

**Comment by Johnstone-Tech** [comment] 2018-08-29 09:47
looks like a duplicate of #31

**Comment by itJunky** [comment] 2018-10-09 01:08
Have same error, but it different with https://github.com/Nanoseb/ncTelegram/issues/31

**Comment by Nanoseb** [comment] 2018-10-30 18:08
duplicate of #39 , closing (fixed in master)

**Closed by Nanoseb** 2018-10-30 18:08 UTC
